# Generated by Django 4.1.3 on 2024-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='supplies',
            field=models.ManyToManyField(related_name='ideas', to='sparklabapi.supply'),
        ),
    ]
