# Generated by Django 4.1.3 on 2024-08-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0002_alter_idea_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='ideas',
            field=models.ManyToManyField(related_name='ideas', to='sparklabapi.idea'),
        ),
    ]
