# Generated by Django 4.1.3 on 2024-08-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0003_collection_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='img',
            field=models.URLField(),
        ),
    ]
