# Generated by Django 4.1.3 on 2024-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0004_alter_idea_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
