# Generated by Django 4.1.3 on 2024-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0005_alter_idea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='img',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
