# Generated by Django 4.1.3 on 2024-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0006_alter_idea_img_alter_idea_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=800),
        ),
    ]
