# Generated by Django 4.1.3 on 2024-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabapi', '0009_alter_idea_description_alter_idea_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
